### ISSUE TITLE
Update to 3.0.109

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [moosefs/moosefs-freebsd-ports#2]
Hello, 

The current FreeBSD port is two versions behind. Please update the port to 3.0.105.

**Comment by pkonopelko** [comment]
Hello @jSML4ThWwBID69YC,

Thanks for raising the issue. We are going to release MooseFS 3.0.107 soon (see [recent commits](https://github.com/moosefs/moosefs/commits/master)) and just after it is done I will update the ports to that version.

Thanks for using MooseFS!

Best regards,
Piotr / MooseFS Team

**Comment by jSML4ThWwBID69YC** [comment]
Hello @pkonopelko 

That's awesome news. 

I'm testing MooseFS against the recent Fuse rewrite on FreeBSD. (https://svnweb.freebsd.org/base?view=revision&revision=352351) 

Is it worth testing 3.0.103, or I should I wait for 3.0.107?

**Comment by pkonopelko** [comment]
Hello @jSML4ThWwBID69YC,

To be honest, we have made a lot of improvements since 3.0.103 (see [NEWS file](https://github.com/moosefs/moosefs/blob/master/NEWS)), so I think that you should use the newest version. If you don't want to wait, you can download the latest MooseFS source tarball and in `freebsd` directory you will find `makeports.sh` script. Use it this way:

```
cd moosefs-master/freebsd
mkdir ports-3.0.107
./makeports.sh ports-3.0.107
```
The script generates FreeBSD ports – they may be slightly different than these in FreeBSD official ports, but should work well.

Regarding recent changes in FreeBSD FUSE implementation, @cemeyer asked us to test the recent changes, but we were quite busy with many fixes. Hopefully we will find time to do it in the near future. Mose of the issues were related to caching, see https://github.com/moosefs/moosefs/issues/89 for reference. 

Best regards,
Piotr / MooseFS Team

**Comment by jSML4ThWwBID69YC** [comment]
Hello @pkonopelko ,

The Fuse fixes in FreeBSD are part of 12.1-RELEASE which is supposed to be released on November 4th. I've been testing the RC2 candidate. 

If 3.0.107 is releasing in the next week or so, I'll test it on the 12.1-RELEASE version. I'll try and trigger the main issue listed in https://github.com/moosefs/moosefs/issues/89 to verify that is fixed. 

Thank you.

**Comment by jSML4ThWwBID69YC** [comment]
Hello @pkonopelko 

Ping. Can the port be upgraded to v3.0.107.

**Comment by pkonopelko** [comment]
Hello @jSML4ThWwBID69YC,
Once 3.0.109 gets released, I will update the ports tree.

Best regards,
Piotr / MooseFS Team

**Comment by jSML4ThWwBID69YC** [comment]
Hello @pkonopelko 

Thank you for the update. Is there an issue with 3.0.107 that prevents it from being used? I was hoping to start testing soon.

**Comment by pkonopelko** [comment]
Hello @jSML4ThWwBID69YC,
There are several minor issues related to the CGI interface / CGI Server. There is one important (already fixed) issue in Master Server and it is related to removing directories – `rmdir` packet size ([fixed here](https://github.com/moosefs/moosefs/commit/c56310fd1d9f43f7b0894dbb12527dce5cd75414)). You can see all the recent commits and changelog [here](https://github.com/moosefs/moosefs/compare/v3.0.107...master).

If nothing new comes up I believe that this week we should finish testing, release 3.0.109, prepare the ports, commit them in this repo and submit them at FreeBSD Bugzilla to be included in the official ports tree.

Thank you for your patience!

Best regards,
Piotr / MooseFS Team

**Comment by pkonopelko** [comment]
Hello @jSML4ThWwBID69YC,

MooseFS 3.0.109 [has been released](https://github.com/moosefs/moosefs/releases/tag/v3.0.109). I will be working on updating the ports soon.

Best regards,
Piotr / MooseFS Team

**Comment by jSML4ThWwBID69YC** [comment]
Hello @pkonopelko 

Thank you.

**Comment by jSML4ThWwBID69YC** [comment]
Hello @pkonopelko 

Has the update been submitted? It's still showing 3.0.103 as the latest version.

**Comment by jSML4ThWwBID69YC** [comment]
bump

**Comment by pkonopelko** [comment]
Hello @jSML4ThWwBID69YC,

I have made a changes to ports and raised PR on FreeBSD Bugzilla (link to the bug [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=243376)) in order to get the ports updated. Once it is committed, I will do appropriate commit in this repository.

For now I have merged recent changes that were made in official FreeBSD ports tree with this mirror in order to maintain consistency (see commit: e13bd93).

I am sorry that you had to wait so long.

Best regards,
Piotr / MooseFS Team

**Comment by cemeyer** [comment]
Kudos Piotr, thanks for updating the port!  Sorry FUSE was broken on our end for so long, too. :-)

**Comment by pkonopelko** [comment]
Hi @cemeyer,

Thanks :) Yes, FUSEFS is much better now, we removed most of the workarounds in MooseFS code. By the way – do you think that working on https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230259#c7 would be possible sometime soon? It seems that it is the last issue left.

Best regards,
Piotr / MooseFS Team

**Comment by jSML4ThWwBID69YC** [comment]
Thank you @pkonopelko and thanks to everybody who improved FUSEFS and MooseFS on FreeBSD.
